# Generated by Django 3.0.5 on 2020-04-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_about_you_hightlight_hobbies_project_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birth', models.DateField()),
                ('gender_Marital_Status', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=250)),
            ],
        ),
    ]
